# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hash_map.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dkvs.HashMap" do
    map :pairs, :string, :string, 1
  end
end

module Dkvs
  HashMap = Google::Protobuf::DescriptorPool.generated_pool.lookup("dkvs.HashMap").msgclass
end
